# Generated by Django 2.2.2 on 2019-06-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planners', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItems',
            new_name='FoodItem',
        ),
    ]
